#!/bin/bash

prog=$0
here=$(echo $prog|sed 's,/[^/]*$,,')
here=`(cd "$here"; pwd)`
prog=$(echo "$prog"|sed 's,^.*/,,')

wm=$(echo "$prog"|sed 's,xde-startwm-,,')
wm=${1:-${wm:-fluxbox}}

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/etc/xdg}

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}

dirs=$(echo "$XDG_DATA_HOME:$XDG_DATA_DIRS"|sed 's,:, ,g')

# setup fluxbox

export_FLUXBOX() {
    FBWM_CONFIG_HOME=${FBWM_CONFIG_HOME:-$XDG_CONFIG_HOME/fluxbox}
    if [ -z "$FBWM_CONFIG_SDIR" ]; then
	FBWM_CONFIG_SDIR="/usr/share/fluxbox"
	for d in $dirs; do
	    if [ -r "$d/fluxbox/version" ]; then
		FBWM_CONFIG_SDIR="$d/fluxbox"
		break fi done fi
    FBWM_RCFILE=${FBWM_RCFILE:-$FBWM_CONFIG_HOME/init};

    export FBWM_CONFIG_HOME
    export FBWM_CONFIG_SDIR
    export FBWM_RCFILE
}
setup_FLUXBOX() { :
}
start_FLUXBOX() { :
}

# setup blackbox

export_BLACKBOX() {
    BBWM_CONFIG_HOME=${BBWM_CONFIG_HOME:-$XDG_CONFIG_HOME/blackbox}
    if [ -z "$BBWM_CONFIG_SDIR" ]; then
	BBWM_CONFIG_SDIR="/usr/share/blackbox"
	for d in $dirs; do
	    if [ -r "$d/blackbox/version" ]; then
		BBWM_CONFIG_SDIR="$d/blackbox"
		break
	    fi
	done
    fi
    BBWM_RCFILE=${BBWM_RCFILE:-$BBWM_CONFIG_HOME/rc};

    export BBWM_CONFIG_HOME
    export BBWM_CONFIG_SDIR
    export BBWM_RCFILE
}
setup_BLACKBOX() { :
}
start_BLACKBOX() { :
}

# setup openbox

export_OPENBOX() {
    OBWM_CONFIG_HOME=${OBWM_CONFIG_HOME:-$XDG_CONFIG_HOME/openbox}
    if [ -z "$OBWM_CONFIG_SDIR" ]; then
	OBWM_CONFIG_SDIR="/usr/share/openbox"
	for d in $dirs; do
	    if [ -r "$d/openbox/version" ]; then
		OBWM_CONFIG_SDIR="$d/openbox"
		break
	    fi
	done
    fi
    OBWM_RCFILE=${OBWM_RCFILE:-$OBWM_CONFIG_HOME/xde-rc.xml}

    export OBWM_CONFIG_HOME
    export OBWM_CONFIG_SDIR
    export OBWM_RCFILE
}
setup_OPENBOX() { :
}
start_OPENBOX() { :
}

# setup icewm

export_ICEWM() {
    ICEWM_CONFIG_HOME=${ICEWM_CONFIG_HOME:-$XDG_CONFIG_HOME/icewm}
    if [ -z "$ICEWM_CONFIG_SDIR" ]; then
	ICEWM_CONFIG_SDIR="/usr/share/icewm"
	for d in $dirs; do
	    if [ -r "$d/icewm/version" ]; then
		ICEWM_CONFIG_SDIR="$d/icewm"
		break
	    fi
	done
    fi
    ICEWM_RCFILE=${ICEWM_RCFILE:-$ICEWM_CONFIG_HOME/preferences}

    export ICEWM_CONFIG_HOME
    export ICEWM_CONFIG_SDIR
    export ICEWM_RCFILE
}
setup_ICEWM() { :
}
start_ICEWM() { :
}

# setup JWM

export_JWM() {
    JWM_CONFIG_HOME=${JWM_CONFIG_HOME:-$XDG_CONFIG_HOME/jwm}
    if [ -z "$JWM_CONFIG_SDIR" ]; then
	JWM_CONFIG_SDIR="/usr/share/jwm"
	for d in $dirs; do
	    if [ -r "$d/jwm/version" ]; then
		JWM_CONFIG_SDIR="$d/jwm"
		break
	    fi
	done
    fi
    JWM_RCFILE=${JWM_RCFILE:-$JWM_CONFIG_HOME/rc}

    export JWM_CONFIG_HOME
    export JWM_CONFIG_SDIR
    export JWM_RCFILE
}
setup_JWM() { :
}
start_JWM() { :
}

# setup PEK

export_PEKWM() {
    PEKWM_CONFIG_HOME=${PEKWM_CONFIG_HOME:-$XDG_CONFIG_HOME/pekwm}
    if [ -z "$PEKWM_CONFIG_SDIR" ]; then
	PEKWM_CONFIG_SDIR="/usr/share/pekwm"
	for d in $dirs; do
	    if [ -r "$d/pekwm/version" ]; then
		PEKWM_CONFIG_SDIR="$d/pekwm"
		break
	    fi
	done
    fi

    export PEKWM_CONFIG_HOME
    export PEKWM_CONFIG_SDIR
    export PEKWM_RCFILE
}
setup_PEKWM() { :
}
start_PEKWM() { :
}

# setup FVWM

export_FVWM() {
    FVWM_CONFIG_HOME=${FVWM_CONFIG_HOME:-${FVWM_USERDIR:-$XDG_CONFIG_HOME/fvwm}}
    if [ -z "$FVWM_CONFIG_SDIR" ]; then
	FVWM_CONFIG_SDIR="/usr/share/fvwm"
	for d in $dirs; do
	    if [ -r "$d/fvwm/version" ]; then
		FVWM_CONFIG_SDIR="$d/fvwm"
		break
	    fi
	done
    fi
    FVWM_RCFILE=${FVWM_RCFILE:-$FVWM_CONFIG_HOME/rc}

    export FVWM_CONFIG_HOME
    export FVWM_CONFIG_SDIR
    export FVWM_RCFILE
}
setup_FVWM() { :
}
start_FVWM() { :
}

# setup WindowMaker

export_WMAKER() {
    WMKR_CONFIG_HOME=${WMKR_CONFIG_HOME:-${GNUSTEP_USER_ROOT:-$XDG_CONFIG_HOME/GNUstep}}
    if [ -z "$WMKR_CONFIG_SDIR" ]; then
	WMKR_CONFIG_SDIR="/usr/share/WindowMaker"
	for d in $dirs; do
	    if [ -r "$d/WindowMaker/version" ]; then
		WMKR_CONFIG_SDIR="$d/WindowMaker"
		break
	    fi
	done
    fi
    WMKR_RCFILE=${WMKR_RCFILE:-$WMKR_CONFIG_HOME/Defaults/WindowMaker}

    export WMKR_CONFIG_HOME
    export WMKR_CONFIG_SDIR
    export WMKR_RCFILE
}
setup_WMAKER() { :
}
start_WMAKER() { :
}

# setup CTWM

export_CTWM() {
    CTWM_CONFIG_HOME=${CTWM_CONFIG_HOME:-$XDG_CONFIG_HOME/ctwm}
    if [ -z "$CTWM_CONFIG_SDIR" ]; then
	CTWM_CONFIG_SDIR="/usr/share/ctwm"
	for d in $dirs; do
	    if [ -r "$d/ctwm/version" ]; then
		CTWM_CONFIG_SDIR="$d/ctwm"
		break
	    fi
	done
    fi
    CTWM_RCFILE=${CTWM_RCFILE:-$CTWM_CONFIG_HOME/rc.m4}

    export CTWM_CONFIG_HOME
    export CTWM_CONFIG_SDIR
    export CTWM_RCFILE
}
setup_CTWM() { :
}
start_CTWM() { :
}

# setup VTWM

export_VTWM() {
    VTWM_CONFIG_HOME=${VTWM_CONFIG_HOME:-$XDG_CONFIG_HOME/vtwm}
    if [ -z "$VTWM_CONFIG_SDIR" ]; then
	VTWM_CONFIG_SDIR="/usr/share/vtwm"
	for d in $dirs; do
	    if [ -r "$d/vtwm/version" ]; then
		VTWM_CONFIG_SDIR="$d/vtwm"
		break
	    fi
	done
    fi
    VTWM_RCFILE=${VTWM_RCFILE:-$VTWM_CONFIG_HOME/rc.m4}

    export VTWM_CONFIG_HOME
    export VTWM_CONFIG_SDIR
    export VTWM_RCFILE
}
setup_VTWM() { :
}
start_VTWM() { :
}

# setup TWM

export_TWM() {
    TWM_CONFIG_HOME=${TWM_CONFIG_HOME:-$XDG_CONFIG_HOME/twm}
    if [ -z "$TWM_CONFIG_SDIR" ]; then
	TWM_CONFIG_SDIR="/usr/share/twm"
	for d in $dirs; do
	    if [ -r "$d/twm/version" ]; then
		TWM_CONFIG_SDIR="$d/twm"
		break
	    fi
	done
    fi
    TWM_RCFILE=${TWM_RCFILE:-$TWM_CONFIG_HOME/rc}

    export TWM_CONFIG_HOME
    export TWM_CONFIG_SDIR
    export TWM_RCFILE
}
setup_TWM() { :
}
start_TWM() { :
}

export_ALL() {
    export_FLUXBOX
    export_BLACKBOX
    export_OPENBOX
    export_ICEWM
    export_JWM
    export_PEKWM
    export_FVWM
    export_WMAKER
    export_CTWM
    export_VTWM
    export_TWM
}

export_ALL

case "$wm" in
(fluxbox|Fluxbox)
    setup_FLUXBOX
    start_FLUXBOX
    ;;
(blackbox|Blackbox)
    setup_BLACKBOX
    start_BLACKBOX
    ;;
(openbox|openbox-session|Openbox)
    setup_OPENBOX
    start_OPENBOX
    ;;
(icewm|icewm-session|IceWM)
    setup_ICEWM
    start_ICEWM
    ;;
(jwm|JWM)
    setup_JWM
    start_JWM
    ;;
(pekwm|PEK|PEKWM)
    setup_PEKWM
    start_PEKWM
    ;;
(fvwm|fvwm2|FVWM|FVMW2)
    setup_FVWM
    start_FVWM
    ;;
(wmaker|WindowMaker)
    setup_WMAKER
    start_WMAKER
    ;;
(ctwm|CTWM)
    setup_CTWM
    start_CTWM
    ;;
(vtwm|VTWM)
    setup_VTWM
    start_VTWM
    ;;
(twm|TWM)
    setup_TWM
    start_TWM
    ;;
esac


# vim: set sw=4:
