#!/bin/bash

config=$0
here=$(echo $config|sed 's,/[^/]*$,,')
(cd "$here"; here=`pwd`)
config=$(echo "$config"|sed 's,^.*/,,')
config="$here/$config";
setstyle="$here/setstyle"

TWM_TYPE=${1:-${TWM_TYPE:-twm}}
TWM_VERSION=${2:-${TWM_VERSION:-1.0.8}}

echo "twm program is: $TWM_TYPE $TWM_VERSION" >&2

TWM_CONFIG_HOME=${TWM_CONFIG_HOME:-$HOME/.$TWM_TYPE}
TWM_CONFIG_SDIR=${TWM_CONFIG_SDIR:-/usr/share/$TWM_TYPE}

[ -d "$TWM_CONFIG_HOME" ] || mkdir -p "$TWM_CONFIG_HOME"

[ -x "$setstyle" ] || setstyle="$TWM_CONFIG_HOME/setstyle"
[ -x "$setstyle" ] || setstyle="$TWM_CONFIG_SDIR/setstyle"
[ -x "$setstyle" ] || { echo "ERROR: missing setstyle program" >&2; exit 1; }

getstyles() {
    echo "divert(FUNCTIONS)dnl"
    echo "divert(MENUS)dnl"

    echo "Menu \"twmstyles\" (twm_deffore:twm_defback)"
    echo "{"

    echo -e "    \"System Styles\"\t\tf.title"
    find "$TWM_CONFIG_SDIR/looks" -name lookrc 2>/dev/null | sort | while read f
    do
	styledir=$(echo "$f"|sed 's,/lookrc$,,')
	style=$(echo "$styledir"|sed 's,^.*/,,')
	echo "divert(FUNCTIONS)dnl"
	echo "Function \"set-system-style-$style\" { f.exec \"$setstyle TWM_TYPE $styledir\" f.function \"reconfig\" }"
	echo "divert(MENUS)dnl"
	echo -e "    \"$style\"\t\tf.function \"set-system-style-$style\""
    done

    echo -e "    \"User Styles\"\t\tf.title"
    find "$TWM_CONFIG_HOME/looks" -name lookrc 2>/dev/null | sort | while read f
    do
	styledir=$(echo "$f"|sed 's,/lookrc$,,')
	style=$(echo "$styledir"|sed 's,^.*/,,')
	echo "divert(FUNCTIONS)dnl"
	echo "Function \"set-user-style-$style\" { f.exec \"$setstyle TWM_TYPE $styledir\" f.function \"reconfig\" }"
	echo "divert(MENUS)dnl"
	echo -e "    \"$style\"\t\tf.function \"set-user-style-$style\""
    done

    echo "}"
    echo "divert(-1)"
    echo "dnl vim: ft=m4"
}

rcfile="$TWM_CONFIG_HOME/rc.m4"
[ -s "$rcfile" ] || rcfile="$TWM_CONFIG_SDIR/rc.m4"
[ -s "$rcfile" ] || { echo "ERROR: missing file $rcfile" >&2; exit 1; }

for file in apps config defaults keys menu setstyle stylemenu winmenu
do
    if [ ! -f "$TWM_CONFIG_HOME/$file" -a -s "$TWM_CONFIG_SDIR/$file" ]
    then
	cp "$TWM_CONFIG_SDIR/$file" "$TWM_CONFIG_HOME/$file"
    fi
done

getstyles >"$TWM_CONFIG_HOME/stylemenu"

export TWM_CONFIG_HOME
export TWM_CONFIG_SDIR

WIDTH=$(xwininfo -root|grep 'Width:'|awk '{print$2}')
HEIGHT=$(xwininfo -root|grep 'Height:'|awk '{print$2}')

CLASS=$(xwininfo -root|grep 'Visual Class:'|awk '{print$3}')
case "$CLASS" in
(*Color)    COLOR='Yes' ;;
(*)	    COLOR='No' ;;
esac

USER=${LOGNAME:-$USER}

m4 -DUSER="$USER" -DHOME="$HOME" \
   -DWIDTH="$WIDTH" -DHEIGHT="$HEIGHT" \
   -DCLASS="$CLASS" -DCOLOR="$COLOR" \
   -DTWM_TYPE="$TWM_TYPE" -DTWM_VERSION="$TWM_VERSION" \
   "$rcfile" >"$TWM_CONFIG_HOME/rc"

# vim: sw=4
