#!/bin/bash

getstyles=$0
here=$(echo $getstyles|sed 's,/[^/]*$,,')
here=`(cd "$here"; pwd)`
getstyles=$(echo "$getstyles"|sed 's,^.*/,,')
getstyles="$here/$getstyles";
setstyle="$here/setstyle"

TWM_TYPE=${1:-${TWM_TYPE:-twm}}

TWM_CONFIG_HOME=${TWM_CONFIG_HOME:-$HOME/.$TWM_TYPE}
TWM_CONFIG_SDIR=${TWM_CONFIG_SDIR:-/usr/share/$TWM_TYPE}
USER=${LOGNAME:-$USER}

[ -d "$TWM_CONFIG_HOME" ] || mkdir -p "$TWM_CONFIG_HOME"

[ -x "$setstyle" ] || setstyle="$TWM_CONFIG_HOME/setstyle"
[ -x "$setstyle" ] || setstyle="$TWM_CONFIG_SDIR/setstyle"
[ -x "$setstyle" ] || { echo "ERROR: missing setstyle program" >&2; exit 1; }

getstyles() {
    echo "divert(FUNCTIONS)dnl"
    echo "divert(MENUS)dnl"

    echo "Menu \"twmstyles\" (twm_deffore:twm_defback)"
    echo "{"

    echo -e "    \"System Styles\"\t\tf.title"
    find "$TWM_CONFIG_SDIR/looks" -name lookrc 2>/dev/null | sort | while read f
    do
	styledir=$(echo "$f"|sed 's,/lookrc$,,')
	style=$(echo "$styledir"|sed 's,^.*/,,')
	echo "divert(FUNCTIONS)dnl"
	echo "Function \"set-system-style-$style\" { f.exec \"$setstyle TWM_TYPE $styledir\" f.function \"reconfig\" }"
	echo "divert(MENUS)dnl"
	echo -e "    \"$style\"\t\tf.function \"set-system-style-$style\""
    done

    echo -e "    \"User Styles\"\t\tf.title"
    find "$TWM_CONFIG_HOME/looks" -name lookrc 2>/dev/null | sort | while read f
    do
	styledir=$(echo "$f"|sed 's,/lookrc$,,')
	style=$(echo "$styledir"|sed 's,^.*/,,')
	echo "divert(FUNCTIONS)dnl"
	echo "Function \"set-user-style-$style\" { f.exec \"$setstyle TWM_TYPE $styledir\" f.function \"reconfig\" }"
	echo "divert(MENUS)dnl"
	echo -e "    \"$style\"\t\tf.function \"set-user-style-$style\""
    done

    echo "}"
    echo "divert(-1)"
    echo "dnl vim: ft=m4"
}

getstyles >"$TWM_CONFIG_HOME/stylemenu"

exit 0

# vim: sw=4
