#!/bin/bash

if [ $# -gt 1 ] ; then
    TWM_TYPE="$1"
    styledir="$2"
else
    TWM_TYPE=${TWM_TYPE:-vtwm}
    styledir="$1"
fi

[ -n "$styledir" ] || { echo "ERROR" >&2; exit 1; }
[ -d "$styledir" ] || { echo "ERROR" >&2; exit 1; }

TWM_CONFIG_HOME="${TWM_CONFIG_HOME:-$HOME/.$TWM_TYPE}"

[ -d "$TWM_CONFIG_HOME" ] || mkdir -p "$TWM_CONFIG_HOME"

rm -f "$TWM_CONFIG_HOME/lookrc"
ln -s "$styledir/lookrc" "$TWM_CONFIG_HOME/"

cat >"$TWM_CONFIG_HOME/look"<<TWMEOF
divert(-1)
define(\`TWM_STYLE_DIR',\`$styledir')
sinclude(\`$styledir/lookrc')
dnl vim:ft=m4
TWMEOF

exit 0

# vim: sw=4

