#!/bin/bash

prog=$0
here=$(echo $prog|sed 's,/[^/]*$,,')
here=`(cd "$here"; pwd)`
prog=$(echo "$prog"|sed 's,^.*/,,')

if [ $# -gt 1 ] ; then
    VTWM_TYPE=${1:-${VTWM_TYPE:-vtwm}}
    styledir="$2"
else
    VTWM_TYPE=${VTWM_TYPE:-vtwm}
    styledir="$1"
fi

[ -n "$styledir" ] || { echo "ERROR" >&2; exit 1; }
[ -d "$styledir" ] || { echo "ERROR" >&2; exit 1; }

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME:-~}/.config}
VTWM_CONFIG_HOME=${VTWM_CONFIG_HOME:-$XDG_CONFIG_HOME/$VTWM_TYPE}

[ -d "$VTWM_CONFIG_HOME" ] || mkdir -p "$VTWM_CONFIG_HOME"

rm -f "$VTWM_CONFIG_HOME/stylerc"
ln -s "$styledir/stylerc" "$VTWM_CONFIG_HOME/"

cat >"$VTWM_CONFIG_HOME/style"<<TWMEOF
divert(-1)
define(\`TWM_STYLE_DIR',\`$styledir')
sinclude(\`$styledir/stylerc')
dnl vim:ft=m4
TWMEOF

exit 0

# vim: sw=4

