#!/bin/bash

style="$1"

if test -n "$style" -a -f "$style"; then
	cat >"${JWM_CONFIG_DIR:-$HOME/.jwm}/style"<<EOF
<?xml version="1.0"?>
<JWM>
   <Include>$style</Include>
</JWM>
EOF
	jwm -restart
fi
